### ISSUE TITLE
Apple Match-O Librarian Error

### ISSUE THREAD

**Issue by fabnoe** [Isuru-Nanayakkara/IJReachability#7]
I am iOS 8.2 using CocoaPods. What's missing here?

error: /Applications/Xcode-Beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: unknown option character `X' in: -Xlinker
Usage: /Applications/Xcode-Beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-sacLT] [-no_warning_for_no_symbols]
Usage: /Applications/Xcode-Beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -dynamic [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-o output] [-install_name name] [-compatibility_version #] [-current_version #] [-seg1addr 0x#] [-segs_read_only_addr 0x#] [-segs_read_write_addr 0x#] [-seg_addr_table <filename>] [-seg_addr_table_filename <file_system_path>] [-all_load] [-noall_load]

**Comment by Isuru-Nanayakkara** [comment]
Hi, yesterday I renamed the project from Swift-Reachability to IJReachability. I modified the .podspec file and in the process, something must have gone wrong. I'm aware of the problem and currently looking into it. 

In the meantime you can simply add the IJReachability.swift file to your project and keep working. I'll update you once I get the issue resolved.

Sorry about that.

**Comment by Isuru-Nanayakkara** [comment]
Got it! The issue is fixed. You can add the library using CocoaPods now.
```
pod 'IJReachability', :git => 'https://github.com/Isuru-Nanayakkara/IJReachability.git'
```
