### ISSUE TITLE
Cannot invoke 'withUnsafePointer' HELP

### ISSUE THREAD

**Issue by geennari** [Isuru-Nanayakkara/IJReachability#8]
So I'm getting this error and I can't find a solution, help.

Cannot invoke 'withUnsafePointer' with an argument list of type '(inout sockaddr_in, () -> _)
```swift
let defaultRouteReachability = withUnsafePointer(&zeroAddress)
```

**Comment by Isuru-Nanayakkara** [comment]
Sorry about the late response. Unfortunately I can't replicate your issue. The `IJReachability.swift` file gives no errors in Swift 1.2.

**Comment by geennari** [comment]
No problem, I had other problems this past week. I'm updating xcode and swift now. Going to test again later and update here. Thanks in advance.
